import { VocabularyItem } from '../types/vocab';

export const INITIAL_VOCABULARY: Omit<VocabularyItem, 'id' | 'createdAt'>[] = [
  // --- CHAPTER 1: Greetings & Introductions ---
  {
    japanese: 'こんにちは',
    reading: 'こんにちは',
    romaji: 'konnichiwa',
    english: 'Hello, Good afternoon',
    type: 'Expression',
    source: 'Textbook',
    chapter: 1,
    acceptedMeanings: ['hello', 'good afternoon', 'hi'],
    categories: ['Greetings', 'Chapter 1'],
    notes: 'Standard daytime greeting.',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: 'ありがとう',
    reading: 'ありがとう',
    romaji: 'arigatou',
    english: 'Thank you, Thanks',
    type: 'Expression',
    source: 'Textbook',
    chapter: 1,
    acceptedMeanings: ['thank you', 'thanks'],
    categories: ['Greetings', 'Chapter 1'],
    notes: 'Informal thank you.',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: 'すみません',
    reading: 'すみません',
    romaji: 'sumimasen',
    english: 'Excuse me, I am sorry',
    type: 'Expression',
    source: 'Textbook',
    chapter: 1,
    acceptedMeanings: ['excuse me', 'i am sorry', 'sorry', 'pardon me'],
    categories: ['Greetings', 'Chapter 1'],
    notes: 'Used for apologizing, thanking, or calling a waiter.',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '先生',
    reading: 'せんせい',
    romaji: 'sensei',
    english: 'Teacher, Professor, Doctor',
    type: 'Noun',
    source: 'Textbook',
    chapter: 1,
    acceptedMeanings: ['teacher', 'a teacher', 'professor', 'doctor'],
    categories: ['People', 'Chapter 1'],
    notes: 'Honorific title for teachers and doctors.',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '学生',
    reading: 'がくせい',
    romaji: 'gakusei',
    english: 'Student',
    type: 'Noun',
    source: 'Textbook',
    chapter: 1,
    acceptedMeanings: ['student', 'a student'],
    categories: ['People', 'Chapter 1'],
    notes: 'University or general student.',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },

  // --- CHAPTER 2: Daily Items & Possessions ---
  {
    japanese: '本',
    reading: 'ほん',
    romaji: 'hon',
    english: 'Book',
    type: 'Noun',
    source: 'Textbook',
    chapter: 2,
    acceptedMeanings: ['book', 'a book'],
    categories: ['Daily Life', 'Chapter 2'],
    notes: 'Also counter for long cylinder items.',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '車',
    reading: 'くるま',
    romaji: 'kuruma',
    english: 'Car, Vehicle, Automobile',
    type: 'Noun',
    source: 'Textbook',
    chapter: 2,
    acceptedMeanings: ['car', 'a car', 'vehicle', 'automobile'],
    categories: ['Travel', 'Chapter 2'],
    notes: 'Kanji appears in 電車 (densha - train).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '時計',
    reading: 'とけい',
    romaji: 'tokei',
    english: 'Watch, Clock',
    type: 'Noun',
    source: 'Textbook',
    chapter: 2,
    acceptedMeanings: ['watch', 'clock', 'a clock', 'a watch'],
    categories: ['Daily Life', 'Chapter 2'],
    notes: 'Wristwatch is 腕時計 (udedokei).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '傘',
    reading: 'かさ',
    romaji: 'kasa',
    english: 'Umbrella',
    type: 'Noun',
    source: 'Textbook',
    chapter: 2,
    acceptedMeanings: ['umbrella', 'an umbrella'],
    categories: ['Daily Life', 'Chapter 2'],
    notes: 'Essential in Japanese rainy season (つゆ).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },

  // --- CHAPTER 3: Places, Food & Drink ---
  {
    japanese: '水',
    reading: 'みず',
    romaji: 'mizu',
    english: 'Water, cold water',
    type: 'Noun',
    source: 'Textbook',
    chapter: 3,
    acceptedMeanings: ['water', 'cold water'],
    categories: ['Food', 'Chapter 3'],
    notes: 'Hot water is お湯 (oyu).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: 'お茶',
    reading: 'おちゃ',
    romaji: 'ocha',
    english: 'Tea, Green tea',
    type: 'Noun',
    source: 'Textbook',
    chapter: 3,
    acceptedMeanings: ['tea', 'green tea'],
    categories: ['Food', 'Chapter 3'],
    notes: 'Traditional Japanese green tea.',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: 'ご飯',
    reading: 'ごはん',
    romaji: 'gohan',
    english: 'Cooked rice, Meal',
    type: 'Noun',
    source: 'Textbook',
    chapter: 3,
    acceptedMeanings: ['rice', 'cooked rice', 'meal', 'a meal'],
    categories: ['Food', 'Chapter 3'],
    notes: 'Morning meal is 朝ご飯 (asagohan).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '魚',
    reading: 'さかな',
    romaji: 'sakana',
    english: 'Fish',
    type: 'Noun',
    source: 'Textbook',
    chapter: 3,
    acceptedMeanings: ['fish', 'a fish'],
    categories: ['Food', 'Chapter 3'],
    notes: 'Raw fish is 刺身 (sashimi).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },

  // --- CHAPTER 4: Time & Basic Actions ---
  {
    japanese: '食べる',
    reading: 'たべる',
    romaji: 'taberu',
    english: 'To eat, eat',
    type: 'Verb',
    source: 'Textbook',
    chapter: 4,
    acceptedMeanings: ['to eat', 'eat'],
    categories: ['Verbs', 'Chapter 4'],
    notes: 'Ichidan verb. Polite: 食べます (tabemasu).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'medium',
    learningStatus: 'New'
  },
  {
    japanese: '飲む',
    reading: 'のむ',
    romaji: 'nomu',
    english: 'To drink, drink',
    type: 'Verb',
    source: 'Textbook',
    chapter: 4,
    acceptedMeanings: ['to drink', 'drink'],
    categories: ['Verbs', 'Chapter 4'],
    notes: 'Godan verb. Polite: 飲みます (nomimasu).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'medium',
    learningStatus: 'New'
  },
  {
    japanese: '行く',
    reading: 'いく',
    romaji: 'iku',
    english: 'To go, go',
    type: 'Verb',
    source: 'Textbook',
    chapter: 4,
    acceptedMeanings: ['to go', 'go'],
    categories: ['Verbs', 'Chapter 4'],
    notes: 'Te-form is irregular: 行って (itte).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'medium',
    learningStatus: 'New'
  },
  {
    japanese: '見る',
    reading: 'みる',
    romaji: 'miru',
    english: 'To see, look, watch',
    type: 'Verb',
    source: 'Textbook',
    chapter: 4,
    acceptedMeanings: ['to see', 'see', 'to look', 'look', 'to watch', 'watch'],
    categories: ['Verbs', 'Chapter 4'],
    notes: 'Ichidan verb. Polite: 見ます (mimasu).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'medium',
    learningStatus: 'New'
  },
  {
    japanese: '時間',
    reading: 'じかん',
    romaji: 'jikan',
    english: 'Time, hours',
    type: 'Noun',
    source: 'Textbook',
    chapter: 4,
    acceptedMeanings: ['time', 'hours', 'hour'],
    categories: ['Daily Life', 'Chapter 4'],
    notes: 'Span of time, e.g. 1時間 (1 hour).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },

  // --- CHAPTER 5: Adjectives & Descriptions ---
  {
    japanese: '大きい',
    reading: 'おおきい',
    romaji: 'ookii',
    english: 'Big, large',
    type: 'Adjective',
    source: 'Textbook',
    chapter: 5,
    acceptedMeanings: ['big', 'large'],
    categories: ['Adjectives', 'Chapter 5'],
    notes: 'I-adjective. Negative: 大きくない (ookikunai).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '小さい',
    reading: 'ちいさい',
    romaji: 'chiisai',
    english: 'Small, little',
    type: 'Adjective',
    source: 'Textbook',
    chapter: 5,
    acceptedMeanings: ['small', 'little'],
    categories: ['Adjectives', 'Chapter 5'],
    notes: 'I-adjective. Negative: 小さくない (chiisaikunai).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '新しい',
    reading: 'あたらしい',
    romaji: 'atarashii',
    english: 'New, fresh',
    type: 'Adjective',
    source: 'Textbook',
    chapter: 5,
    acceptedMeanings: ['new', 'fresh'],
    categories: ['Adjectives', 'Chapter 5'],
    notes: 'I-adjective. Opposite: 古い (furui).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '美味しい',
    reading: 'おいしい',
    romaji: 'oishii',
    english: 'Delicious, tasty',
    type: 'Adjective',
    source: 'Textbook',
    chapter: 5,
    acceptedMeanings: ['delicious', 'tasty', 'yummy'],
    categories: ['Adjectives', 'Chapter 5'],
    notes: 'Casual: うまい (umai).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },

  // --- EXTRA VOCABULARY (Non-textbook) ---
  {
    japanese: '桜',
    reading: 'さくら',
    romaji: 'sakura',
    english: 'Cherry blossom, Cherry tree',
    type: 'Noun',
    source: 'Extra',
    category: 'Daily Life',
    acceptedMeanings: ['cherry blossom', 'cherry blossoms', 'cherry tree'],
    categories: ['Nature', 'Daily Life', 'Extra'],
    notes: 'Symbol of Japanese spring.',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '日本',
    reading: 'にほん',
    romaji: 'nihon',
    english: 'Japan',
    type: 'Noun',
    source: 'Extra',
    category: 'Travel',
    acceptedMeanings: ['japan'],
    categories: ['Travel', 'Extra'],
    notes: 'Also pronounced にっぽん (nippon).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '猫',
    reading: 'ねこ',
    romaji: 'neko',
    english: 'Cat',
    type: 'Noun',
    source: 'Extra',
    category: 'Daily Life',
    acceptedMeanings: ['cat', 'a cat'],
    categories: ['Animals', 'Daily Life', 'Extra'],
    notes: 'Very popular household animal in Japan.',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '犬',
    reading: 'いぬ',
    romaji: 'inu',
    english: 'Dog',
    type: 'Noun',
    source: 'Extra',
    category: 'Daily Life',
    acceptedMeanings: ['dog', 'a dog'],
    categories: ['Animals', 'Daily Life', 'Extra'],
    notes: 'Famous Hachiko statue in Shibuya is an Akita dog.',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  },
  {
    japanese: '友達',
    reading: 'ともだち',
    romaji: 'tomodachi',
    english: 'Friend, Companion',
    type: 'Noun',
    source: 'Extra',
    category: 'Conversation',
    acceptedMeanings: ['friend', 'friends', 'companion'],
    categories: ['People', 'Conversation', 'Extra'],
    notes: 'Compound of 友 (friend) + 達 (plural suffix).',
    practiceCount: 0,
    correctCount: 0,
    wrongCount: 0,
    consecutiveCorrect: 0,
    difficulty: 'easy',
    learningStatus: 'New'
  }
];
